# Generated by Django 5.2 on 2025-04-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='coin_balance',
            field=models.IntegerField(default=0, help_text="User's current coin balance."),
        ),
    ]
