# Generated by Django 5.2 on 2025-04-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_coin_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='coin_balance',
            field=models.IntegerField(default=25, help_text="User's current coin balance."),
        ),
    ]
