# Generated by Django 5.2 on 2025-04-08 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_coin_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='assigned_moderator',
            field=models.ForeignKey(blank=True, help_text='Moderator assigned to manage this fake profile (only relevant if is_fake=True).', limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_fake_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='moderator_notes',
            field=models.TextField(blank=True, help_text='Internal notes for moderators about this user (especially if real user).', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text="User's profile picture.", null=True, upload_to='profile_pics/'),
        ),
    ]
