# Generated by Django 5.2 on 2025-04-10 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_customuser_profile_picture_userprofileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileimage',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Is this image approved by admin/moderator?'),
        ),
    ]
