# Generated by Django 5.2 on 2025-04-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customuser_birth_date_customuser_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='about_me',
            field=models.TextField(blank=True, help_text='A short description about the user.', null=True, verbose_name='About Me'),
        ),
    ]
