# Generated by Django 5.2 on 2025-04-22 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_customuser_gender_customuser_seeking_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='seeking_gender',
            new_name='seeking',
        ),
    ]
