# Generated by Django 5.2 on 2025-04-11 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationAiSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_mode', models.CharField(choices=[('NONE', 'No AI Support'), ('ASSISTED', 'AI Assisted Replies'), ('AUTO', 'AI Automatic Replies')], default='NONE', help_text='Select the AI operation mode for this specific conversation.', max_length=10, verbose_name='AI Mode')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fake_user', models.ForeignKey(limit_choices_to={'is_fake': True}, on_delete=django.db.models.deletion.CASCADE, related_name='ai_settings_as_fake_user', to=settings.AUTH_USER_MODEL, verbose_name='Fake User')),
                ('real_user', models.ForeignKey(limit_choices_to={'is_fake': False}, on_delete=django.db.models.deletion.CASCADE, related_name='ai_settings_as_real_user', to=settings.AUTH_USER_MODEL, verbose_name='Real User')),
            ],
            options={
                'verbose_name': 'Conversation AI Setting',
                'verbose_name_plural': 'Conversation AI Settings',
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('real_user', 'fake_user'), name='unique_ai_setting_per_conversation')],
            },
        ),
    ]
