# Generated by Django 5.2 on 2025-04-27 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('like', 'Neuer Like'), ('message', 'Neue Nachricht'), ('system', 'Systemnachricht')], help_text='Art der Benachrichtigung', max_length=20)),
                ('content', models.TextField(help_text='Inhalt der Benachrichtigung')),
                ('is_read', models.BooleanField(default=False, help_text='Gibt an, ob die Benachrichtigung gelesen wurde')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung der Benachrichtigung')),
                ('reference_id', models.IntegerField(blank=True, help_text='ID des referenzierten Objekts (z.B. Like-ID, Nachrichten-ID)', null=True)),
                ('reference_model', models.CharField(blank=True, help_text="Name des referenzierten Modells (z.B. 'Like', 'Message')", max_length=50, null=True)),
                ('sender', models.ForeignKey(blank=True, help_text='Benutzer, der die Aktion ausgelöst hat (falls zutreffend)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='Benutzer, der die Benachrichtigung erhält', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Benachrichtigung',
                'verbose_name_plural': 'Benachrichtigungen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_info', models.TextField(help_text='JSON-String mit den Abonnementinformationen')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung des Abonnements')),
                ('last_used', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Verwendung des Abonnements')),
                ('user', models.ForeignKey(help_text='Benutzer, dem dieses Push-Abonnement gehört', on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Push-Abonnement',
                'verbose_name_plural': 'Push-Abonnements',
            },
        ),
    ]
